require('plugins_config.nvim-tree')
require('plugins_config.lualine')
require('plugins_config.telescope')
require('plugins_config.treesitter')
require('plugins_config.completions')
require('plugins_config.nvim-jupyter-client')
require('plugins_config.iron')
